---
title: "About me"
---

I recently finished my third year of the Political Science PhD program at the University of Minnesota. My interests are in American politics, political economy, political geography, and political methodology.

I am involved in student leadership and service here at UMN. I have been a member of the Council of Graduate Students for two years, and prior to that I was on the University Senate as the graduate student representative for the College of Liberal Arts. I have organized my department's American Politics Colloquium for the past two years.

Before joining my current department, I was a graduate student in the School of Statistics (2017-2020), a Technical Services Analyst at Epic (2015-2017), and an undergrad (Math and Environmental Studies) at Wellesley College. I grew up in Northeast Ohio.

In my spare time, I like to travel. I'd been to 48 states by the age of seven, though it took another 22 years to get the 49th. I believe I'll likely never get the 50th, though I've always been a fan of perfect squares so I will accept this. I also like to play strategy games, watch Cleveland sports (Minnesota sports are also acceptable), go on walks around my local lake, and eat good food. I am a fan of fall, gardening, and ebikes.